### ISSUE TITLE
Expanding on Docker for/on Windows difference

### ISSUE THREAD

**Issue by glennsarti** [portainer/portainer-docs#10]
There are some fundamental differences between Docker on Windows vs Docker for Windows but I don't feel the documentation spells these out very well, for example, the on vs for distinction is still quite vague.

I would like to suggest some documentation changes to help with this:

1. Use the term Windows Containers (or something else that is far more distinguishable) to refer to the native docker engine on Windows and use Docker for Windows when referring to the Linux Containers in VM on Windows.

2. Add some links so people can get more information on the two different types of platforms for Docker.

3. Add a new page of documentation which goes into more depth about the differences between the two

4. Add information on how to determine which one a user has e.g. `do docker version.  Look for the OS/Arch of the Server

5.  Reference the Docker On Windows page in the quick start guide so that this will keep the quick start small, but still provide places to go to learn more.

**Comment by deviantony** [comment]
I do agree that we need to make the documentation clearer and easily accessible for Docker beginners. Unfortunately, Docker made it confusing by introducing the naming Docker **for** Windows and Docker **on** Windows. I'm not sure that we should explain/guide the user on the differences between both (or maybe just slightly) even if our goal is to make Docker accessible for everyone we don't want to play the role of Docker support.

Documentation **IS** really important and we should rewrite it to be easier for our users to understand but for that we'll probably need more feedback (thanks @glennsarti for yours!).

@ncresswell what do you think on about this topic?

**Comment by ncresswell** [comment]
We should clarify the difference to make it easier for our users... if not, we spend a lot of time answering the same questions.

Rgds,

Neil Cresswell

On 13/01/2017, at 12:29 PM, Anthony Lapenna <notifications@github.com<mailto:notifications@github.com>> wrote:


I do agree that we need to make the documentation clearer and easily accessible for Docker beginners. Unfortunately, Docker made it confusing by introducing the naming Docker for Windows and Docker on Windows. I'm not sure that we should explain/guide the user on the differences between both (or maybe just slightly) even if our goal is to make Docker accessible for everyone we don't want to play the role of Docker support.

Documentation IS really important and we should rewrite it to be easier for our users to understand but for that we'll probably need more feedback (thanks @glennsarti<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_glennsarti&d=DQMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=0fx0h4vB56iTLpw2McH1ZD6TqG_QGpbggVOB-PfMJpM&m=cu941yL3zdpO8evBDLPfU9oOZFq9PkafC-7kXj9vz28&s=XBQc8XmWbxZzjGlQuILHCeikq91cBMdMrogG-E_84Bw&e=> for yours!).

@ncresswell<https://urldefense.proofpoint.com/v2/url?u=https-3A__github.com_ncresswell&d=DQMFaQ&c=euGZstcaTDllvimEN8b7jXrwqOf-v5A_CdpgnVfiiMM&r=0fx0h4vB56iTLpw2McH1ZD6TqG_QGpbggVOB-PfMJpM&m=cu941yL3zdpO8evBDLPfU9oOZFq9PkafC-7kXj9vz28&s=Iyu7IM8RktHEB02NloHMyV9PdhIuRMhWKpIj6XI8fa8&e=> what do you think on about this topic?

-

**Comment by glennsarti** [comment]
Agreed, I certainly would not suggest something too large, but providing links to the relevant products seems like a low-cost thing to do.

Example documentation:
---

## What's the difference between Docker for Windows and Docker on Windows?

Docker for Windows is a Virtual Machine provided by Docker which runs a Linux Container Host on Windows

[Link](https://docs.docker.com/docker-for-windows/)

Docker on Windows is a Docker engine for the native Windows Container Host announced out of the partnership between Docker and Microsoft

[Link](https://www.docker.com/microsoft)

## How can I tell which I'm using?

Run `docker info`

In the server section look for the OS/Arch.  If it says linux, that's Docker for Windows, if it's Windows, that's Docker on Windows (--- or something to that effect ---)



'

**Comment by deviantony** [comment]
@glennsarti I've tried to improve the deployment documentation without asking too much to the user (without asking them to run `docker info` and such) for now... 

With the introduction of a portainer image with multiarch support there is no need to specify the `windows` tag or not anymore, which has also simplified the things.

Can you tell me what you think about it? https://portainer.readthedocs.io/en/stable/deployment.html

**Comment by glennsarti** [comment]
@deviantony I like it.  Only comment is that Windows Containers area available on Windows 10, 2016 and Nano Server.

So perhaps drop the reference to `(Windows Server 2016)` ?

**Comment by deviantony** [comment]
Damn, I need to find a better way to specify the difference then as I'm pretty sure that if I leave *Windows Containers* alone, Docker for Windows users will think they're concerned.
