### ISSUE TITLE
Missing SSL certificates generation section

### ISSUE THREAD

**Issue by menant** [portainer/portainer-docs#103]
Hello team,

I'd like to respectfully highlight that both **docs/v2.0/deploy/ssl.md** and **docs/v2.0-be/deploy/ssl.md**
are missing the part for SSL certificate generation in the section **Securing Portainer using SSL with Docker**.

There is still related information that can be repurposed in **docs/archive/1.23.2/deployment.md**, section **Secure Portainer using SSL**

I hope this helps.
Thank you for your effort.

**Comment by Anthony-Portainer** [comment]
Hi,

Thanks for raising this with us, we'll get that sorted out.

Ant

**Comment by menant** [comment]
Thank you for your response.
If that helps, I'll be happy to follow your recommended steps and report back afterwards if I encounter any problem.

**Comment by Anthony-Portainer** [comment]
That would be great, thanks. Will be in touch soon!

Ant
