### ISSUE TITLE
View Deleted Docker Containers' logs in Portainer?

### ISSUE THREAD

**Issue by haneef95** [portainer/portainer-docs#108]
Hi,

Is it possible to view the logs of deleted containers in Portainer?

https://github.com/portainer/portainer-docs/blob/master/docs/v2.0/containers/logs.md

Thanks,

**Comment by PortainerSupport** [comment]
Ticket update by Anthony McMahon (Anthony.mcmahon@portainer.io)

Hi,

There is no history of deleted containers kept, so once they are gone the logs
will go as well.

Ant
