### ISSUE TITLE
How do I use Docker Compose to create a Kubernetes env with Portainer

### ISSUE THREAD

**Issue by samuelarogbonlo** [portainer/portainer-docs#139]
I have a docker-compose file but I need to create a K8s env with portainer, are there documentations and advice that I can use to go about this?

**Comment by samdulam** [comment]
Hi,

You can manage a Kubernetes Cluster using Portainer but not create one. If that is what you are trying to do.

If you are looking to deploy into Kubernetes using docker-compose file you may do so via Portainer.
![image](https://user-images.githubusercontent.com/58716812/116502509-c763be00-a907-11eb-899a-757d62668fe2.png)

**Comment by samuelarogbonlo** [comment]
So how do I host a k8s cluster on portainer itself?

**Comment by samdulam** [comment]
You can not host on Portainer.
You can only **manage existing** Docker / Swarm / Kubernetes environments using Portainer.
