### ISSUE TITLE
PortainerCE and traefik reverse proxy

### ISSUE THREAD

**Issue by wildbeastking** [portainer/portainer-docs#149]
Hi, frontend and edge in traefik labels are deprecated in traefik:latest version

https://documentation.portainer.io/v2.0/ad/traefik/rp-traefik/ - Here use frontend and edge

https://doc.traefik.io/traefik/migration/v1-to-v2/#frontends-and-backends-are-dead-long-live-routers-middlewares-and-services - Proof

**Comment by samdulam** [comment]
Hi @wildbeastking 

I believe we are already using `traefik.http.routers.` labels. 'Frontend' is just an arbitrary name like router0.

Regards
