### ISSUE TITLE
Custom Templates -> How to use git repository

### ISSUE THREAD

**Issue by MrVBian** [portainer/portainer-docs#161]
I refer to the official document: [https://documentation.portainer.io/v2.0/stacks/create/](https://documentation.portainer.io/v2.0/stacks/create/)

Gihub:
<img width="1917" alt="1" src="https://user-images.githubusercontent.com/37790267/121769030-ebb3eb00-cb93-11eb-8650-3c40fca180e3.png">
<img width="1908" alt="2" src="https://user-images.githubusercontent.com/37790267/121769033-ee164500-cb93-11eb-92ea-ac7546e0a038.png">

Error: “Get https://544207374@qq.com:***@github.com/MrVBian/test//info/refs?service=git-upload-pack: EOF”

Password I use Personal access tokens

**Comment by jamescarppe** [comment]
It looks like you're using your email address instead of your Github username here. Try with the username and see how you get on.
