### ISSUE TITLE
portainer-templates

### ISSUE THREAD

**Issue by BigPapoo** [portainer/portainer-docs#19]
Hi.
Need for more detailed explanation in the Doc. I'm able to create a new nginx container that serves a templates.json but how/where do I setup this in portainer so it queries my own template repository ? I cloned the official one (as suggested in the doc) and I just changed some template titles to see if something changes but it seems to keep querying the online repository. Did I miss something ? Thx.

**Comment by BigPapoo** [comment]
Ok, got it working, you need to add a "--templates=http://<your_nginx_container>/templates.json" as an argument to /portainer ENTRYPOINT. Depending on the way you run it it can be a "command" entry in a docker-compose file or an argument on your "docker run" command line.
Documentation should really be improved to explain this. Thanks.

**Comment by deviantony** [comment]
@BigPapoo have you seen this section http://portainer.readthedocs.io/en/stable/configuration.html#use-your-own-templates ?

**Comment by BigPapoo** [comment]
It seems I missed it :-) Thanks!
