### ISSUE TITLE
Wrong Command in Agent Installation for Windows

### ISSUE THREAD

**Issue by Nefarion** [portainer/portainer-docs#216]
https://github.com/portainer/portainer-docs/blob/ce-2.9/start/install/agent/docker/wcs.md

The provided command does not work, there should be double backslashes before the pipe...
`docker run -d -p 9001:9001 -e CAP_HOST_MANAGEMENT=1 --name portainer_agent --restart=always -v C:\:C:\host -v C:\ProgramData\docker\volumes:C:\ProgramData\docker\volumes -v \.\pipe\docker_engine:\.\pipe\docker_engine portainer/agent:latest`

should be ________________________________________________________________________________________________________________________________________________________________________________________________vv (here) _________________vv (and here)
`docker run -d -p 9001:9001 -e CAP_HOST_MANAGEMENT=1 --name portainer_agent --restart=always -v C:\:C:\host -v C:\ProgramData\docker\volumes:C:\ProgramData\docker\volumes -v \\.\pipe\docker_engine:\\.\pipe\docker_engine portainer/agent:latest`

Thanks for the great tool!

**Comment by jamescarppe** [comment]
Good catch. This has been fixed in 185a2f4bbcebdff9b30071ca14f92d5a3d95ab91 and 6c2be8d8c6930d88b407507c79e965d7248048a2 .
