### ISSUE TITLE
Documentation is broken

### ISSUE THREAD

**Issue by Eitol** [portainer/portainer-docs#220]
![image](https://user-images.githubusercontent.com/1043061/136709692-93db9baa-688f-4f75-973d-c998c1dee5a2.png)

**Comment by jamescarppe** [comment]
Thanks for submitting an issue for this! This is a result of issues at Gitbook which we are working with them to resolve ASAP. They will be updating the status at https://www.gitbookstatus.com/incidents/xthvgt8dcx8b as they work to resolve the problems.

**Comment by Eitol** [comment]
Solved
