### ISSUE TITLE
I cannot pull docker images from custom registry 

### ISSUE THREAD

**Issue by yongnights** [portainer/portainer-docs#222]
my portainer is 1.24.2，A custom image registry has been added。
When I enter the image and pull it，The error information is as follows:
```
{"message":"pull access denied for xxxx:tag, 
repository does not exist or may require 'docker login': 
denied: requested access to the resource is denied"}
```

But I have configured the registry address, user name and password on the custom registry page.

**Comment by jamescarppe** [comment]
This repository is for the Portainer documentation specifically. For issues relating to Portainer itself, please open them in the [Portainer repository](https://github.com/portainer/portainer/issues).
