### ISSUE TITLE
Wrong Port in Setup.

### ISSUE THREAD

**Issue by illmaren** [portainer/portainer-docs#226]
https://github.com/portainer/portainer-docs/blob/ce-2.11/start/install/server/docker/linux.md

docker run -d -p 8000:8000 -p 9443:9443 --name portainer \
    --restart=always \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v portainer_data:/data \
    portainer/portainer-ce:2.11.0

Port 8000 is wrong here it needs to be Port 9000

**Comment by jamescarppe** [comment]
`8000` is correct. As mentioned earlier in the document:

> By default, Portainer Server will expose the UI over port `9443` and expose a TCP tunnel server over port `8000`. The latter is optional and is only required if you plan to use the Edge compute features with Edge agents.

**Comment by f2ka07** [comment]
Portainer Port 9000 is only used for legacy reasons, you need to get used to using [portainer ports 8000 and 9443](https://solid-future.com/docs/portainers-port-8000-9443-and-9000-in-docker-management/).  Port 8000 is for remote agents while port 9443 is for SSL.
