### ISSUE TITLE
Slow to access Dashboard.

### ISSUE THREAD

**Issue by fgodoy** [portainer/portainer-docs#228]
I don't know if it's my fault, but, everytime that I try to access dashboard they are so slow. After a couple of minutes everything start faster.
Maybe anyone can help me? 

Thanks a lot. 

Attached network that cut after 1 minute. 
<img width="957" alt="Screenshot_2" src="https://user-images.githubusercontent.com/2242629/151194136-8b8266ee-7588-43ce-82c9-e3e4f5caa24c.png">

**Comment by jamescarppe** [comment]
This repository is specifically for the Portainer documentation. If you have issues with Portainer itself, please open an issue in the [portainer/portainer](https://github.com/portainer/portainer/issues) repository.
