### ISSUE TITLE
Docs don't include directions on upgrading edge agents

### ISSUE THREAD

**Issue by claycooper** [portainer/portainer-docs#230]
The docs don't include directions on upgrading edge agents. Since they're install differently from regular agents I assume upgrading is also different. Can details on how to upgrade or a note saying to upgrade the same as regular agents be added so it's not ambiguous?

**Comment by jamescarppe** [comment]
Good catch - we are indeed missing these instructions at present. I'll start writing these up.

**Comment by jamescarppe** [comment]
Upgrading instructions for the Edge Agent are now available [in the documentation](https://docs.portainer.io/v/ce-2.11/start/upgrade/edge).
