### ISSUE TITLE
Variables in custom Template?

### ISSUE THREAD

**Issue by kimdre** [portainer/portainer-docs#231]
How do you set and use variables in custom templates like those in some of your templates?

The [documentation](https://github.com/portainer/portainer-docs/blob/4683e8430551807145e618b823f81bb4bab442a1/user/docker/templates/custom.md) doesn't describe how to do this.

![image](https://user-images.githubusercontent.com/27567533/155146696-620a88ed-39b6-4b05-ad2b-9290b6002ccf.png)

![image](https://user-images.githubusercontent.com/27567533/155146899-841ab7d1-da36-426c-88b3-1840bda86635.png)

**Comment by jamescarppe** [comment]
This functionality is part of the App Templates functionality and not currently available in Custom Templates. You can create your own templates.json file containing your custom templates and load that into Portainer. You can find more about this particular feature of App Templates [here](https://docs.portainer.io/v/ce-2.11/advanced/app-templates/format#env-1).
