### ISSUE TITLE
Autogen PDF of Docs

### ISSUE THREAD

**Issue by 0cwa** [portainer/portainer-docs#234]
Gitbook offers functionality to generate a pdf https://docs.gitbook.com/features/pdf-export

Would be nice for putting the docs on an e-reader.

(I looked into gitbook-cli for epub and mobi too but it wouldn't work and is not maintained)

**Comment by jamescarppe** [comment]
We've looked at this as an option, however this feature is only available on the higher end plans and would more than quadruple our monthly Gitbook bill, which we can't justify for just this feature.
