### ISSUE TITLE
Install Portainer on your Kubernetes environment without persistent volume

### ISSUE THREAD

**Issue by shakibamoshiri** [portainer/portainer-docs#240]
Dear maintainer of this link [Install Portainer on your Kubernetes environment](https://docs.portainer.io/v/ce-2.11/start/install/server/kubernetes/baremetal) 
It would be better to add a `yaml` file without a need for Persistent Volume and Storage Class for a quick test.

Your document is pretty clean and readable -- but I failed to test it on a local environment and finally removed **Persistent Volume Claim and mount path** from the `yaml` file to test and see the first look and feel of Portainer.

**Comment by jamescarppe** [comment]
We recommend referring to the [latest documentation](https://docs.portainer.io/start/install/server/kubernetes/baremetal) for install instructions.

As the installation instructions mention, Portainer _requires_ a persistent volume and StorageClass configured to run on Kubernetes, and providing an installation option without those pieces (even just for testing) would likely lead to significant confusion for users trying to get set up.
