### ISSUE TITLE
No more webhooks?

### ISSUE THREAD

**Issue by VirgileD** [portainer/portainer-docs#241]
Hello!
I just updated an old portainer version that was running an early 2 version. I updated to 2.14.1 CE. It is "managing" a docker swarm of 3 nodes.
I can't find the "Service webhook" switch on the service detail page, is it normal?
We use this extensively to make the deployment process more easy.
Maybe I missed an option somewhere?

**Comment by jamescarppe** [comment]
This repository is for the Portainer documentation rather than Portainer itself - I'd suggest reposting this in [the Portainer repository](https://github.com/portainer/portainer/issues).
