### ISSUE TITLE
Wrong referenced hyper link - Method 2 under "Add a Docker Standalone environment" 

### ISSUE THREAD

**Issue by ranabanerjee15** [portainer/portainer-docs#246]
Hello Docker Team,

The referenced link under:

Method 2: Connecting via the Portainer Agent

> platform-specific instructions

do not work, it gives a 404

![image](https://user-images.githubusercontent.com/33179430/198578371-1e8d2169-fe97-4606-96e4-c69f0376c9e0.png)

**Comment by jamescarppe** [comment]
This page has been rewritten in 2.16 and removes this link.
