### ISSUE TITLE
Can work windows 's edge agent install script is？

### ISSUE THREAD

**Issue by guoqingkong** [portainer/portainer-docs#248]
docker run -d -p 9001:9001 --name portainer_agent --restart=always -v C:\:C:\host -v C:\ProgramData\docker\volumes:C:\ProgramData\docker\volumes -v \\.\pipe\docker_engine:\\.\pipe\docker_engine portainer/agent:latest

in doc is error  the path style is not be recognized by docker run ... please fix it .

**Comment by jamescarppe** [comment]
It looks like your paths are missing the double backslashes for `\\.\pipe`. Can you provide the URL for the documentation page that has this incorrect?
