### ISSUE TITLE
Insufficient UI / docs for planned deprecated features

### ISSUE THREAD

**Issue by tomumk** [portainer/portainer-docs#26]
Feel free to close this issue and tell me to submit to the main portainer repo if you feel this isn't the right place to discuss this.

Currently, features that are set to be deprecated have no UI elements as the docs claim [here](https://github.com/portainer/portainer-docs/blob/303d54ea0a963e804af9ac5ea39dddb709e5a6fd/docs/source/configuration.rst#deprecated-flags).

I am not sure if hidden-labels has been implemented into container creation under the labels section, or if those labels are not the same as hidden-labels?

My main issue is I cannot find a  settings page, to change the logo or add another template file / endpoint. The docs suggest this is possible, but it doesn't seem to be.

**Comment by deviantony** [comment]
Hi @tomumk thanks for the report !

Did you access the documentation via the badge in our repository? It was pointing at the `latest` version of the documentation (which is the development version, this is not released yet).

The badge has been updated via https://github.com/portainer/portainer/commit/f48423d5aa7ff76f5fe95df85084354d247ede4d and now points at the `stable` version of the documentation (latest release).

**Comment by tomumk** [comment]
Hi @deviantony,

I am not sure which version of the docs I accessed previously, but it seems the stable docs also have the same wording. [Here](https://portainer.readthedocs.io/en/stable/configuration.html#use-your-own-logo) states that you can change the logo in the settings UI, but I cannot see that (on v 1.13.1, so 1 version behind). 

Same applies for the templates, I cannot see a way to change / add templates via the settings UI either as [here](https://portainer.readthedocs.io/en/stable/configuration.html#use-your-own-templates) claims I should be able to.

If this was added in v 1.13.2, then I will update and you can close this issue. Otherwise this is a docs problem, or a feature missing from [portainer/portainer](https://github.com/portainer/portainer) and nobody has noticed.

**Comment by deviantony** [comment]
Hey @tomumk ! 1.13.2 has been released yesterday and the docs where updated at that time too :-)

**Comment by tomumk** [comment]
Just checked out [demo.portainer.io](http://demo.portainer.io/) and seems you are correct.
Thanks for the fast responses, and your work on portainer.
