### ISSUE TITLE
Trying to host portainer-docs locally - `ERROR: unknown block tag: hint`

### ISSUE THREAD

**Issue by Cloufish** [portainer/portainer-docs#264]
I'm trying to host portainer-host locally since PDF-Export is not supported -> https://github.com/portainer/portainer-docs/issues/234

I'm using following docker-compose.yml
```yml
version: '3'

services:
  mdbook:
    container_name: portainer-docs
    image: hitzhangjie/gitbook-cli:latest
    # stdin_open: true
    # tty: true
    ports:
      - 4000:4000
    volumes:
      - ${PWD}/portainer-docs:/root/gitbook
    command:

```
It was the best one I've found.

And I get following errors:
`$ gitbook serve`:
```bash
Live reload server started on port: 35729
Press CTRL+C to quit ...

info: 7 plugins are installed
info: loading plugin "livereload"... OK
info: loading plugin "highlight"... OK
info: loading plugin "search"... OK
info: loading plugin "lunr"... OK
info: loading plugin "sharing"... OK
info: loading plugin "fontsettings"... OK
info: loading plugin "theme-default"... OK
info: found 266 pages
info: found 1468 asset files
error: error while generating page "README.md":

Template render error: (/root/gitbook/README.md) [Line 11, Column 2]
  unknown block tag: hint
```

Here's also a docker command for attaching to the container
`docker run -it -v ./portainer-docs/:/root/gitbook --entrypoint /bin/bash hitzhangjie/gitbook-cli:latest`

So it seems like portainer-docs use some sort of a plugin?
I've tried to search for a file in this repo that tells which should I install 

Any help wanted!

**EDIT:** I realized now that `gitbook-cli` is deprecated and only GitBook Platform is maintained. :/

**Comment by jamescarppe** [comment]
> **EDIT:** I realized now that `gitbook-cli` is deprecated and only GitBook Platform is maintained. :/

Yeah, this is the case. I believe the version of Gitbook that the CLI tool was made for is a much older version, and Gitbook have reworked their product significantly since then. 

The intent behind this repository is not really for users to host it locally, but to provide a method for users to submit updates to the documentation where needed.
