### ISSUE TITLE
Update Docs for Deploying Portainer behind Nginx Reverse Proxy

### ISSUE THREAD

**Issue by qnlbnsl** [portainer/portainer-docs#267]
https://github.com/portainer/portainer-docs/blame/fa34d77d7295e20740389882aa1f1d8d6c27bf59/advanced/reverse-proxy/nginx.md#L143

The documentation for deploying portainer behind nginx reverse proxy shows that log level can be `debug`. Using it as is causes the agent to not start up as it is expecting `DEBUG`

**Comment by jamescarppe** [comment]
Thanks for flagging this - I've [updated the example](https://github.com/portainer/portainer-docs/commit/bf51a67b463d26337ff9c482a2111ac4d7d17208#diff-b63eecbc6e97aeacbeb0beaad2e2263a9be41aa9d0ec22b5b3ef1e31081bfa66) alongside other updates for our latest release.
