### ISSUE TITLE
Conflicting information for Custom App Templates in terms of bind-mount

### ISSUE THREAD

**Issue by shantanoo-desai** [portainer/portainer-docs#269]
## Description

URI: https://docs.portainer.io/advanced/app-templates/build

It mentions the following sentence:

> The best way to do this is to [bind-mount your own template file](https://github.com/advanced/cli#defining-your-own-app-templates) directly into the Portainer container. You can also build your own container that will use Nginx to serve the template definitions.

It mentions explicitly to mount the templates JSON file _INTO_ the portainer container. However upon clicking on the Link which is redirected to https://docs.portainer.io/advanced/cli#defining-your-own-app-templates, it explicitly mentions the following command:

```bash
docker run -d -p 9443:9443 -p 8000:8000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer-ce:latest --templates http://my-host.my-domain/templates.json
```

which is not a bind-mount but hosting the templates file via a file server (nginx). Nowhere can one bind information about bind-mounts.

### Expectations

either there should be mention of `bind-mounts` into the container or remove this mention in the documentation if there is no such feature

**Comment by jamescarppe** [comment]
Thanks for flagging this here and on Slack - I've updated documentation with correct instructions.
