### ISSUE TITLE
Update knowledge base for AzureAD authentication

### ISSUE THREAD

**Issue by emanuelezambrano** [portainer/portainer-docs#271]
### Before you start please confirm the following.

- [X] Yes, I've searched similar issues on [GitHub](https://github.com/portainer/portainer/issues).
- [X] Yes, I've checked whether this issue is covered in the Portainer [documentation](https://docs.portainer.io) or [knowledge base](https://portal.portainer.io/knowledge).

### Problem Description

Enabling OAuth Azure AD authentication following your knowledge base, I can't log in (unauthorized popup showed).

You must update the knowledge base by adding the "Grant admin consent for ..." at step 6.
With this additional setting, I solved the problem.

### Expected Behavior

Correctly login with AzureAD user.

### Actual Behavior

Denied login (Unautorized)

### Steps to Reproduce

Follow the knowledge base article [https://docs.portainer.io/admin/settings/authentication/oauth#microsoft](url)

### Portainer version

2.19.4

### Portainer Edition

Business Edition (BE/EE) with 5NF / 3NF license

### Platform and Version

Kubernetes 1.26

### OS and Architecture

Ubuntu

**Comment by jamescarppe** [comment]
I have shifted this to the portainer-docs repo as it is a documentation update rather than a bug with the application itself.

**Comment by jamescarppe** [comment]
Documentation has now been updated for the changes to the Azure AD process since we initially wrote this.
