### ISSUE TITLE
No documentation on running portainer in a subdirectory.

### ISSUE THREAD

**Issue by Spylon** [portainer/portainer-docs#34]
I can't find any documentation on how to configure portainer to run in a subdirectory.

For example my.domain.dom/portainer

Thanks!

**Comment by deviantony** [comment]
Hi @Spylon 

Sorry for the late update, have you looked at file:///home/tony/workspaces/portainer/portainer-docs/docs/build/html/faq.html#how-can-i-configure-my-reverse-proxy-to-serve-portainer ?
