### ISSUE TITLE
The nginx proxy example should change.

### ISSUE THREAD

**Issue by leogzl** [portainer/portainer-docs#36]
Using nginx version: nginx/1.13.7, the current config will show error: `404 Page not found`

Using this config will solve this issue.
The proxy for api is not necessary anymore.
```
	location ~ ^/portainer/(.*)$ {
		proxy_pass              http://portainer/$1;
		proxy_redirect          off;
		proxy_set_header        Host            $host;
		proxy_set_header        X-Real-IP       $remote_addr;
		proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
		client_max_body_size    10m;
		client_body_buffer_size 128k;
		proxy_connect_timeout   90;
		proxy_send_timeout      90;
		proxy_read_timeout      90;
		proxy_buffers           32 4k;
	}
```

**Comment by leogzl** [comment]
Need to put this too on the server config:
`rewrite ^/portainer /portainer/ redirect;`
to ensure the redirection goes to the path portainer/.

**Comment by deviantony** [comment]
Oh good to know, thanks for reporting that ! Mind opening a PR to change the FAQ?

**Comment by leogzl** [comment]
@deviantony DONE.

**Comment by isobit** [comment]
Link to PR: https://github.com/portainer/portainer-docs/pull/38

**Comment by deviantony** [comment]
@isobit not sure if example provided in https://github.com/portainer/portainer-docs/pull/38 is working in its current state.

**Comment by isobit** [comment]
@deviantony sure, I was just leaving a link so that others wouldn't have to go digging for the PR when looking at this issue like I did
