### ISSUE TITLE
Current version

### ISSUE THREAD

**Issue by eliassal** [portainer/portainer-docs#41]
Hi Deviantoy, what is the last version of portainer?
I have 1.11 up and running since almost 1 year and I have a container which I use regularly.

In case there is a new version, would my current container based on image 1.11 be still valid or will it break?
Thanks

**Comment by deviantony** [comment]
Hi @eliassal the current version of Portainer is 1.15.5. I believe that version 1.11 was not using persistence yet, you can probably just start a new container using the latest version (checkout our latest instructions: https://portainer.io/install.html) and decide to remove the older container later.

**Comment by eliassal** [comment]
OK thanks, I will do. Yesterday, on a new machine (Docker on windows), I did a pull and was able to run portainer, however, I had failure to connect to local (myIP:2375) and the other remote (Docker fo windows), cannot connect to both.

**Comment by deviantony** [comment]
@eliassal ensure the Docker API is exposed on both of these hosts.

**Comment by eliassal** [comment]
Thanks, correct, it was a port issue in spite of the fact that I have checked the

"Expose daemon on tcp://localhost:2375", this was not sufficient, I needed to add the following line in the daemon.json
"hosts": ["tcp://192.210.3.6:2375", "npipe://"
It is working like a charm and can connect to my local docker (docker on windows) and remote docker (Docker for windows)
For slack, is this a sort of a forum or newsletter...?

**Comment by eliassal** [comment]
last question, I would like to persist the data and use always the same container, what is the best option with portainer?

**Comment by deviantony** [comment]
@eliassal you should persist Portainer data when you create the container, have a look at http://portainer.readthedocs.io/en/stable/deployment.html#persist-portainer-data
