### ISSUE TITLE
documentation for admin-password is wrong

### ISSUE THREAD

**Issue by ntwrkguru** [portainer/portainer-docs#42]
In the [docs](https://github.com/portainer/portainer-docs/blob/master/docs/source/configuration.rst), the example for using `--admin-password` is incorrect.

It reads:

```$ docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer --admin-password '$2y$05$qFHAlNAH0A.6oCDe1/4W.ueCWC/iTfBMXIHBI97QYfMWlMCJ7N.a6'```

But it should read:

```$ docker run -d -p 9000:9000 -v /var/run/docker.sock:/var/run/docker.sock portainer/portainer --admin-password='$2y$05$qFHAlNAH0A.6oCDe1/4W.ueCWC/iTfBMXIHBI97QYfMWlMCJ7N.a6'```

This is per the contextual help:

```
      --admin-password=ADMIN-PASSWORD  
                                 Hashed
                                 admin
                                 password
```

**Comment by Matts** [comment]
In my testing, this does not seem to matter. Both scenario's start a Portainer instance with the hash in `admin-password` being `$2y$05$qFHAlNAH0A.6oCDe1/4W.ueCWC/iTfBMXIHBI97QYfMWlMCJ7N.a6`

**Comment by ntwrkguru** [comment]
My point was that the contextual help example should match the docs. :-)

**Comment by deviantony** [comment]
Closed via https://github.com/portainer/portainer-docs/commit/546cc73acfe69bb793c8f356dd53373ae59b8fe2
