### ISSUE TITLE
Allow reverse proxy authentication

### ISSUE THREAD

**Issue by trajano** [portainer/portainer-docs#44]
Basically add an authentication mechanism that will accept an HTTP header value such as X-Forwarded-User as the authenticated user.

**Comment by toxic0berliner** [comment]
I find this issue closed but I can't find if it was implemented and don't see a "won't fix" comment here. Can we make portainer login on any request based on a username passes in something like the X-Forwarded-User header ?

**Comment by jamescarppe** [comment]
This repository is specifically for the Portainer documentation. Please post any feature requests for the Portainer product in the [portainer/portainer](https://github.com/portainer/portainer/) repository.
