### ISSUE TITLE
Apache does not proxy websocket.

### ISSUE THREAD

**Issue by danielepercivaldi** [portainer/portainer-docs#46]
I'm using the settings below in order to reverse proxy portainer container that exposes port 9000:
...
<Location /portainer/>
    ProxyPass http://localhost:9000/
    ProxyPassReverse http://localhost:9000/
    RequestHeader set Connection ""
</Location>
<Location /portainer/api/websocket/>
    RequestHeader set Upgrade $http_upgrade;
    RequestHeader set Connection "upgrade"
    ProxyPass ws://localhost:9000/api/websocket/
</Location>
...

These settings are mostly working for me but unfortunately, I am unable to use the console functionality in Portainer. When trying to use the console, my apache log spits out the following error:
AH01144: No protocol handler was valid for the URL /portainer/api/websocket/exec. If you are using a DSO version of mod_proxy, make sure the proxy submodules are included in the configuration using LoadModule. Any ideas?

Thanks.

**Comment by deviantony** [comment]
Unfortunately I cannot really help you with Apache configuration. I'll keep this issue open, feel free to comment if you figure out a solution.

**Comment by Sh4d0wF1gh7** [comment]
Same Problem here...

**Comment by Maximumi** [comment]
```
<Location /portainer/>
ProxyPass http://127.0.0.1:9000/
ProxyPassReverse http://127.0.0.1:9000/
RequestHeader set X-Forwarded-Proto "https"
</Location>

<Location /portainer/api/websocket/>
ProxyPass http://127.0.0.1:9000/api/websocket/
ProxyPassReverse http://127.0.0.1:9000/api/websocket/
RewriteEngine on
RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
RewriteRule /api/websocket/(.*) ws://127.0.0.1:9000/api/websocket/$1 [P]
</Location>
```

Source : https://markus-blog.de/index.php/2018/05/11/how-to-manage-docker-with-portainer-on-ubuntu-16-04-lts-with-apache2-as-reverse-proxy/

**Comment by RolandSM** [comment]
This works for me...

**Comment by danielepercivaldi** [comment]
For me too.
Thanks @Maximumi

**Comment by deehidayat** [comment]
Finally worked.. Thank you guys..

**Comment by iboskov** [comment]
I know this is a closed topic by now, I'll just add this here in case someone comes across the same issue. Since I am using TLS for my hosts, I needed to add wss instead of ws:

<Location /portainer/>
    ProxyPass https://127.0.0.1:9443/
    ProxyPassReverse https://127.0.0.1:9443/
    RequestHeader set X-Forwarded-Proto "https"
</Location>

<Location /portainer/api/websocket/>
    ProxyPass https://127.0.0.1:9443/api/websocket/
    ProxyPassReverse https://127.0.0.1:9443/api/websocket/
    RewriteEngine on
    RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
    RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
    RewriteRule /api/websocket/(.*) wss://127.0.0.1:9443/api/websocket/$1 [P]
</Location>

And don't forget to add LoadModule proxy_wstunnel_module modules/mod_proxy_wstunnel.so in your httpd.conf (below LoadModule proxy_module modules/mod_proxy.so)

**Comment by QuentinCG** [comment]
Thanks a lot,
I needed to change a bit the examples to make it work:

- /etc/apache2/sites-available/portainer.conf
```apache
<VirtualHost *:80>
        ServerName mySuperDomain.com
        ServerAlias www.mySuperDomain.com

        # Enable proxying requests to the Portainer container
        <Location />
                #ProxyPreserveHost On
                ProxyPass http://127.0.0.1:9000/
                ProxyPassReverse http://127.0.0.1:9000/
                RequestHeader set X-Forwarded-Proto "https"
        </Location>

        # WebSocket settings (Proxy to docker container console)
        <Location /api/websocket/>
                ProxyPass http://127.0.0.1:9000/api/websocket/
                ProxyPassReverse http://127.0.0.1:9000/api/websocket/

                RewriteEngine on
                RewriteCond %{HTTP:UPGRADE} ^WebSocket$ [NC]
                RewriteCond %{HTTP:CONNECTION} Upgrade$ [NC]
                RewriteRule /api/websocket/(.*) ws://127.0.0.1:9000/api/websocket/$1 [P,UnsafeAllow3F]
        </Location>
</VirtualHost>
```

- Bash:
```bash
sudo a2enmod rewrite proxy proxy_http proxy_wstunnel headers
sudo systemctl restart apache2

#If using certbot for certificates:
rm /etc/apache2/sites-available/portainer-le-ssl.conf
certbot
```
