### ISSUE TITLE
Document X-PortainerAgent-Target // using Docker API in a Swarm cluster

### ISSUE THREAD

**Issue by lukey78** [portainer/portainer-docs#52]
see https://github.com/portainer/portainer/issues/2016

Correct way for accessing individual nodes via Docker API in a Swarm cluster.

Quoting @deviantony:

"If you send a request without specifying the target header, Portainer will aggregate the containers from all nodes and decorate each container with the NodeName property. Then you can retrieve it and add it as the value of the target header to execute an action on a container inside the cluster."

**Comment by deviantony** [comment]
Closed via https://github.com/portainer/portainer-docs/commit/1d6537b25569a4d216f62fbd6d8aac581e5a35ae
