### ISSUE TITLE
Conflicting info re: stack templates

### ISSUE THREAD

**Issue by Codelica** [portainer/portainer-docs#58]
Current docs state:

> Stack templates can only be deployed inside Swarm clusters via docker stack deploy. Portainer is not compatible with docker-compose at the moment.

Yet they do offer a template type that's compatible with docker-compose (v2) stacks:

> type - Template type, valid values are: 1 (container), 2 (Swarm stack) or 3 (Compose stack).

Might also be worth mentioning that type=3 (Compose stack) templates use the same template params as type=2 (Swarm stack) templates.

**Comment by deviantony** [comment]
Closed via https://github.com/portainer/portainer-docs/commit/e7b7ce55cb4761bf46f8183df71db180f69bda72
