### ISSUE TITLE
FAQ entry for LDAP configuration points to wrong URL

### ISSUE THREAD

**Issue by Brekkjern** [portainer/portainer-docs#59]
The [FAQ entry](https://portainer.readthedocs.io/en/stable/faq.html#how-can-i-enable-ldap-authentication) for configuring Portainer with LDAP points to a URL that does not mention LDAP in any way.

I assume the URL should be to one of these two articles (preferably both since the first has more details on configuring groups and the second has more details on the LDAP configuration itself):
https://www.linkedin.com/pulse/ldap-usersgroups-portainer-neil-cresswell/
https://www.linkedin.com/pulse/how-enable-ldapad-authentication-portainerio-neil-cresswell/

**Comment by deviantony** [comment]
Closed via https://github.com/portainer/portainer-docs/commit/928bb83a89893e7ce261bd67c49de54be51476f1
