### ISSUE TITLE
persistent data hint

### ISSUE THREAD

**Issue by dmnc-net** [portainer/portainer-docs#62]
Hi, I never worked with docker before so you may find me very confused, please be patient.

I'm running docker for testing/dev purposes on my Arch Linux laptop and I'm following the Portainer docs, so I did this:
```
$ docker volume create portainer_data
$ docker run -d -p 9000:9000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v portainer_data:/data portainer/portainer
```
Next, in the [Persist Portainer data](https://portainer.readthedocs.io/en/latest/deployment.html#persist-portainer-data) section I'm confused with "You’ll need to persist Portainer data to keep your changes after restart/upgrade of the Portainer container". But I don't want do a bind mount, I've created the volume which is located in `/var/lib/docker/volumes/portainer_data`. What do you mean by restart of the Portainer container? That means that docker will delete/recreate the volume every time when the service will be started/restarted (i.e. laptop reboot)? This makes on sense to me. Thanks for clarifying

**Comment by deviantony** [comment]
Hi @dmnc-net 

Following the instructions in the quick start section will create a Docker volume and persist the Portainer data inside the volume.

The instruction in the Persist Portainer data section simply shows an example on how to persist Portainer data via a bind mount.

What could we change to make it clearer?

**Comment by mariuszjamro** [comment]
@deviantony 

I also got confused after reading the guide. I think it needs a little info **when** persiting via volume is enough and when persisting via a bind mount is better.

**Comment by madindehead** [comment]
> 
> 
> Hi @dmnc-net
> 
> Following the instructions in the quick start section will create a Docker volume and persist the Portainer data inside the volume.
> 
> The instruction in the Persist Portainer data section simply shows an example on how to persist Portainer data via a bind mount.
> 
> What could we change to make it clearer?

Sorry for commenting on this, but to me it wasn't _clear_ that the data was going to be persisted when created using the command in the quick start section. I found the persist section after I launched the container. By finding this I was certain that my data _was_ going to still be there on a reboot.
