### ISSUE TITLE
The description of the admin-password option is inconsistent in the configuration document

### ISSUE THREAD

**Issue by XhstormR** [portainer/portainer-docs#67]
[This document](https://portainer.readthedocs.io/en/stable/configuration.html#available-flags) say: ``--admin-password``: Admin password in the form ``admin:<hashed_password>``

But in the example usage it is:
```
 --admin-password='$2y$05$qFHAlNAH0A.6oCDe1/4W.ueCWC/iTfBMXIHBI97QYfMWlMCJ7N.a6'
```
One format is `admin:<hashed_password>`, the other format is `<hashed_password>`, I don't understand which format is correct.

**Comment by itsconquest** [comment]
Hi there,
The correct format for the admin password flag is: --admin-password='<hashed_password>' where <hashed_password> is a password you have encrypted using bcrypt, as specified in the documentation.
Cheers
