### ISSUE TITLE
api doc not available

### ISSUE THREAD

**Issue by sunkeysun** [portainer/portainer-docs#69]
https://portainer.readthedocs.io/en/stable/API.html

[Swaggerhub] (https://app.swaggerhub.com/apis/deviantony/Portainer/1.21.0/) is not avaliable, please help fix it. Thanks.

**Comment by deviantony** [comment]
Hi @sunkeysun 

The API documentation at https://app.swaggerhub.com/apis/deviantony/Portainer/1.21.0/ is available. Probably an issue on your side.

**Comment by sunkeysun** [comment]
> Hi @sunkeysun
> 
> The API documentation at https://app.swaggerhub.com/apis/deviantony/Portainer/1.21.0/ is available. Probably an issue on your side.
![image](https://user-images.githubusercontent.com/23015246/59092138-6ca3d080-8943-11e9-8c6e-b0474b953aee.png)
is my screenshot
