### ISSUE TITLE
Is there docker origin api  encapsulated by portainer agent ?

### ISSUE THREAD

**Issue by sunkeysun** [portainer/portainer-docs#70]
I want to update my service or container through portianer api, but can't find some useful api doc at https://app.swaggerhub.com/apis/deviantony/Portainer/1.21.0. Is it possible to call docker origin api（https://docs.docker.com/engine/api/v1.24/）through portainer ?
Please helps. Thanks.

**Comment by deviantony** [comment]
Hi @sunkeysun 

Yes, it is possible. Have a look at the examples available here: https://gist.github.com/deviantony/77026d402366b4b43fa5918d41bc42f8#execute-docker-queries-against-a-specific-endpoint

**Comment by sunkeysun** [comment]
yep! I see. Thanks so mach!
