### ISSUE TITLE
Security Issue with mode=host for published ports

### ISSUE THREAD

**Issue by mback2k** [portainer/portainer-docs#77]
If I am not mistaken your documentation includes a huge security issue in regards to possibly opening up the agent port to the public internet:

`--publish mode=host,target=9001,published=9001`
```
    ports:
      - target: 9001
        published: 9001
        protocol: tcp
        mode: host
```

This is mentioned on the [agent](https://portainer.readthedocs.io/en/stable/agent.html) documentation page multiple times. [Publishing a host port](https://docs.docker.com/compose/compose-file/#long-syntax-1) on each node does not mean that the port is only reachable via localhost on that node. I think there is a huge misunderstanding going on here. It just means that the port is published via iptables on that host and not via Swarm ingress loadbalancing. You are basically telling everyone to publish the agent port to possibly the whole internet if the node has a public IP.

Is this intended? Are other countermeasures taken inside the agent to block public traffic?

**Comment by deviantony** [comment]
This is purely intended. How would you support managing multiple Swarm clusters without being able to remotely connect to your environment? A single Portainer instance can only be deployed in the same overlay network as a single agent cluster (and thus, this one do not need to expose ports publicly).

We are not specifically providing instructions to expose ports over the internet here, these can be used inside your own private network too. In both cases, security considerations must be taken into account on your side.

You can read up more details about the default security mechanism embedded in the agent here: https://github.com/portainer/agent#using-the-agent-non-edge

If you think that the documentation is confusing on this point, we're open to clarify it too.

**Comment by mback2k** [comment]
I am sorry, but the default examples are just including the published ports without warning users about the potential consequences. Of course I have seen the Edge and Secret documentation, but all of that is optional and not mentioned as a requirement in your documentation. As I said, I understood that from the beginning and never deployed an Agent cluster with port 9001 being published. But your documentation encourages just that by default.

The examples should be updated to include an AGENT_SECRET by default if the port is published. And there should probably be big warnings about publishing the ports with such a secret being setup. I understand the use case of remote cluster management you mentioned. But just assume a Swarm cluster on any VPS or Cloud provider there all nodes have public IP addresses assigned to them. Your examples would make the Docker Socket on these nodes accessible other the internet via the Agent if no additional precautions are taken.

**Comment by mback2k** [comment]
I understand that the Agent is basically implemented TOFU (Trust On First Use) via the [Default mode](https://github.com/portainer/agent#default-mode), but what happens if e.g. an Agent restarts and Portainer does not connect to it straight a way. There is definitely a window of opportunity for attack here. I most cases it will be very small, but if Portainer has an issue for example and cannot connect to the Agent quickly, it could be longer than expected. Therefore  IMHO having the ports published is just not a sensible default and shouldn't be the default in all the examples in the docs.

And just closing this issue without waiting for this discussion to be complete first, is not really welcoming behaviour.

**Comment by deviantony** [comment]
@mback2k I am sorry for that I thought this issue was raised in the portainer repository not in the documentation repository. Though the difference is mainly related to our issue workflow.

Nothing wrong with continuing a discussion inside a closed issue, I'll just re-open it. This was just me thinking I answered your question and a such could close the issue.

IMO we should add more details about potential security implications in the documentation and also specify when you need to actually expose the agent port. Feel free to open a PR for this.
