### ISSUE TITLE
Deployment issues: Windows 10 Build 1709

### ISSUE THREAD

**Issue by jsmarsch** [portainer/portainer-docs#90]
For reasons beyond my control, I'm stuck with Win 10 build 1709 (so earlier than some nice docker updates)

I'm having the same problem as in #50 but I'm using the current deploy document.  In that issue, the OP was really using Docker ON Windows Server 2016. (and that was why it didn't work, as discussed in the original thread).  

I'm using Docker FOR Windows (Docker Desktop), with Linux containers (someone posted to #50 that switching to linux containers fixed it for them -- I must be missing something.

I'm using this command (from the docs, I've tried it both from a cmd prompt and from Powershell, same error):
docker run -d -p 9000:9000 -p 8000:8000 --name portainer --restart always -v /var/run/docker.sock:/var/run/docker.sock -v C:\ProgramData\Portainer:/data portainer/portainer

my error; 
docker: Error response from daemon: invalid volume specification: '/var/run/docker.sock:/var/run/docker.sock'.

I would imagine that I need to change: 
-v /var/run/docker.sock:/var/run/docker.sock
to 
-v &lt;some sort of Windows URI&gt;:/var/run/docker.sock

but, that's where I'm stuck -- no idea what to put in &lt;some sort of Windows URI&gt;

**Comment by itsconquest** [comment]
If you are using Linux containers, then `-v /var/run/docker.sock:/var/run/docker.sock` should work.
Can you try this command for windows containers and see if it works `docker run -d --name portainer -v portainer_data:C:\data -v \\.\pipe\docker_engine:\\.\pipe\docker_engine --publish 9000:9000 portainer/portainer`
