### ISSUE TITLE
Alias Recommendation

### ISSUE THREAD

**Issue by cryptic-ai** [portainer/portainer-docs#96]
Good evening! I just wanted to make a recommendation for the portainer docs website. Is there a way that you could also use `docs.portainer.io` and have it routed to the `documenation.portainer.io`? Reason I make this recommendation is it closely resembles other sites (docs.docker.com, docs.microsoft.com) and is easier to share, type, and spread the word. Just food for thought 🙂

**Comment by Anthony-Portainer** [comment]
Hi, good suggestion. Will have a chat internally about how we can do this. 

Ant
